languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Robert Mathew"
copyright = "&copy; 2024"

[params]
  dateFormat = "2 January 2006"

  mainSections = ["samples"]
  description = "Personal site of Robert Mathew"

[params.author]
  name = "Robert Mathew"
  image = "img/author.jpg"
  headline = "I'm only human"
  bio = "A little bit about you"
  links = [
     { github = "https://github.com/robertmathew" },
     { threads = "https://www.threads.net/@silent.robo" },
     { linkedin = "https://www.linkedin.com/in/robertcmathew/" },
     { mastodon = "https://mastodon.social/@silent_robo" }
   ]
